spring:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
      username: TEST
      password: test
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      delete-topic-enable: true
  data:
    mongodb:
      host: localhost
      port: 9000
      database: test
jpa:
  database-platform: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  hibernate:
    format_sql: true
    ddl-auto: create

